import pygame

# Screen dimensions
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (200, 200, 200)
LIGHT_GRAY = (220, 220, 220)
GAME_BG_COLOR = (0, 200, 0)
OPTIONS_BG_COLOR = (0, 0, 200)
INFO_BG_COLOR = (200, 0, 0)
PLAYER_COLOR = (50, 50, 255)
FALLING_SQUARE_COLOR = (255, 50, 50)
TEXT_COLOR_INGAME_INFO = (240, 240, 240)
BUTTON_TEXT_COLOR = BLACK

# Font settings
FONT_DEFAULT_NAME = None # 
FONT_SIZE_LARGE = 50
FONT_SIZE_MEDIUM = 36
FONT_SIZE_SMALL = 30
FONT_SIZE_XSMALL = 28

# Game states
STATE_MAIN_MENU = "main_menu"
STATE_GAME_PLAY = "start_game"
STATE_OPTIONS = "options"
STATE_INFO = "info"

# Player properties
PLAYER_START_X = SCREEN_WIDTH // 2
PLAYER_START_Y = SCREEN_HEIGHT - 50
PLAYER_RADIUS = 20
PLAYER_SPEED = 5
PLAYER_COLOR = PLAYER_COLOR
PLAYER_PNG_PATH = "gameAssets/images/player.png" 
PLAYER_SIZE = 40 

# Button dimensions
BUTTON_WIDTH = 300
BUTTON_HEIGHT = 70
BUTTON_BACK_WIDTH = 350
BUTTON_BACK_HEIGHT = 70

# Background image
BACKGROUND_PNG_PATH = "gameAssets/images/background.jpg" 


FALLING_OBJECT_SIZE = 50
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_WHITE = (255, 255, 255)
FALLING_OBJECT_PNG_PATH_GREEN = "gameAssets/images/apple.png"   #
FALLING_OBJECT_PNG_PATH_RED = "gameAssets/images/sugar.png" 
FALLING_OBJECT_PNG_PATH_WHITE = "gameAssets/images/milk.png"     
FALLING_OBJECT_SPEED = 1
FALLING_OBJECT_SPAWN_RATE = 30